import fs from 'node:fs';
import vm from 'node:vm';
const origin='https://tangzhengpanels.com';
const template=fs.readFileSync('src/template.html','utf8');
const renderer=fs.readFileSync('src/render.js','utf8');
const translation=fs.readFileSync('dist/translations.js','utf8');
const catalog=vm.runInNewContext(translation+';({languages,translations})');
const articleSlug='how-to-choose-insulated-decorative-metal-panels';
const escape=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
for(const lang of Object.keys(catalog.languages)){
 const nodes={};const node=k=>nodes[k]??={innerHTML:'',textContent:'',setAttribute(){},addEventListener(){}};
 const document={documentElement:{},querySelector:node,querySelectorAll:()=>[]};
 vm.runInNewContext(translation+'\n'+renderer,{document,location:{search:'?lang='+lang},URLSearchParams,URL,localStorage:{getItem(){return null}}});
 let html=template.replace(/<html lang="en">/,`<html lang="${lang}" dir="${lang==='ar'?'rtl':'ltr'}">`)
 .replace(/<title>.*?<\/title>/,`<title>${escape(document.title)}</title>`)
 .replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${escape(nodes['meta[name=description]'].content)}">`)
 .replace(/<header>.*?<\/header>/s,`<header>${nodes.header.innerHTML}</header>`)
 .replace(/<div class="hero-copy">.*?<div class="material-art"/s,`<div class="hero-copy">${nodes['.hero-copy'].innerHTML}</div><div class="material-art"`)
 .replace(/<div class="spec-strip">.*?<div id="details"><\/div>/s,`<div class="spec-strip">${nodes['.spec-strip'].innerHTML}</div><div id="details">${nodes['#details'].innerHTML}</div>`)
 .replace(/<footer>.*?<\/footer>/s,`<footer>${nodes.footer.innerHTML}</footer>`)
 .replace(/<script src="translations.js"><\/script>/,'')
 .replace(/(src|href)="(assets\/|style.css|script.js)/g,'$1="/$2');
 const t=catalog.translations[lang];
 html=html.replace('TEXTURE. DEPTH. CHARACTER.',t.texture).replace('Wood, stone and brick metal panel finishes',escape(t.eyebrow));
 ['Rich wood grain metal panel','Grey embossed stone metal panel','Charcoal brick pattern metal panel'].forEach((s,i)=>html=html.replace(s,escape(t.types[[0,4,2][i]])));
 const alternates=Object.keys(catalog.languages).map(l=>`<link rel="alternate" hreflang="${l==='zh'?'zh-Hans':l}" href="${origin}/${l}/">`).join('');
 html=html.replace('</head>',`<link rel="canonical" href="${origin}/${lang}/">${alternates}<link rel="alternate" hreflang="x-default" href="${origin}/en/"></head>`);
 const links=Object.entries(catalog.languages).map(([l,label])=>`<a href="/${l}/" lang="${l}" hreflang="${l}">${label}</a>`).join(' · ');
 html=html.replace('</footer>',`</footer><nav class="language-links" aria-label="${escape(t.lang)}">${links}</nav>`);
 if(lang==='en')html=html.replace('</main>',`<section class="section guide-promo" aria-labelledby="guide-heading"><p class="eyebrow">BUYER'S GUIDE</p><h2 id="guide-heading">How to choose insulated decorative metal panels</h2><p>Compare project conditions, wall assemblies, finishes, samples and supplier documentation before you request a quotation.</p><a class="text-link" href="/en/blog/${articleSlug}/">Read the selection guide →</a></section></main>`);
 fs.mkdirSync('dist/'+lang,{recursive:true});fs.writeFileSync('dist/'+lang+'/index.html',html);
 if(lang==='en')fs.writeFileSync('dist/index.html',html);
}
const article=fs.readFileSync('src/article-en.html','utf8');
fs.mkdirSync(`dist/en/blog/${articleSlug}`,{recursive:true});
fs.writeFileSync(`dist/en/blog/${articleSlug}/index.html`,article);
const markets=[
 {lang:'en',slug:'saudi-arabia',dir:'ltr',title:'Insulated Exterior Wall Panels for Saudi Arabia',description:'TANGZHENG metal carved panels and insulated exterior wall panels for Saudi Arabian villas, warehouses and renovation projects.',heading:'Exterior wall panels for hot-climate projects in Saudi Arabia',lead:'Explore lightweight decorative metal panels that combine an embossed coated-metal surface, insulation core and inner backing. Select the finish and model first, then confirm thermal, fire, wind-load and installation requirements for the project.',keywords:['insulated exterior wall panels Saudi Arabia','decorative metal wall panels','villa exterior cladding','warehouse insulated wall panels'],uses:['Villa and low-rise exterior renovation','Warehouse and workshop wall systems','Modular and prefabricated buildings','Decorative façade upgrades'],checks:['Required thermal performance and wall assembly','Fire-test documentation required by the project','Panel thickness, metal facing and core specification','Wind load, fixings, trims and joint treatment'],faq:[['Are these panels suitable for Saudi Arabia?','They may suit hot-climate wall projects when the selected assembly meets the project’s thermal, fire, structural and weather-resistance requirements. Confirm the complete specification before ordering.'],['Can I request samples?','Yes. Send the texture code, project type, quantity and delivery city to request product information and samples.']]},
 {lang:'ar',slug:'uae',dir:'rtl',title:'ألواح جدران خارجية معدنية معزولة في الإمارات',description:'ألواح TANGZHENG المعدنية الزخرفية والمعزولة للجدران الخارجية والمشاريع السكنية والتجارية في الإمارات.',heading:'ألواح زخرفية ومعزولة لمشاريع الجدران في الإمارات',lead:'مجموعة من الألواح المعدنية المزخرفة بخامات الحجر والطوب والخشب. يجب تأكيد متطلبات الحريق والعزل والرياح والتركيب للنظام الكامل قبل الطلب.',keywords:['ألواح جدران خارجية معزولة','ألواح معدنية زخرفية','كسوة واجهات الإمارات','ألواح عازلة للمباني'],uses:['واجهات الفلل والمباني منخفضة الارتفاع','الجدران الخارجية للمستودعات والورش','المباني الجاهزة والوحدات النمطية','تجديد الواجهات'],checks:['تصنيف الحريق المطلوب للنظام الكامل','الأداء الحراري وسماكة اللوح','مقاومة الرياح والتثبيت','الزوايا والحواف ومعالجة الفواصل'],faq:[['هل تصلح الألواح لجميع المباني؟','يعتمد ذلك على نوع المبنى والارتفاع ومتطلبات الدفاع المدني والمواصفات المعتمدة للمشروع. يجب مراجعة النظام الكامل قبل الاستخدام.'],['كيف أطلب عينة؟','أرسل رقم الموديل ونوع المشروع والكمية ومدينة التسليم عبر البريد الإلكتروني أو واتساب.']]},
 {lang:'ru',slug:'kazakhstan',dir:'ltr',title:'Утеплённые фасадные панели для Казахстана',description:'Декоративные металлические и утеплённые стеновые панели TANGZHENG для домов, складов и реконструкции в Казахстане.',heading:'Утеплённые декоративные панели для проектов в Казахстане',lead:'Выберите фактуру кирпича, камня, дерева или гладкую отделку. Перед заказом согласуйте толщину, сердечник, металлическую облицовку, пожарные требования, крепёж и комплектующие.',keywords:['утеплённые фасадные панели Казахстан','металлические фасадные панели','панели под кирпич','стеновые сэндвич панели'],uses:['Фасады частных и малоэтажных домов','Склады, мастерские и хозяйственные здания','Модульные и быстровозводимые здания','Реконструкция наружных стен'],checks:['Требуемое сопротивление теплопередаче','Пожарные требования конкретного объекта','Толщина панели и материал сердечника','Доборные элементы, крепёж и герметизация стыков'],faq:[['Подходят ли панели для холодного климата?','Возможность применения зависит от расчётной конструкции стены, толщины утепления, стыков и местных требований. Параметры необходимо подтвердить для каждого проекта.'],['Как получить предложение?','Укажите код фактуры, размеры, количество и город доставки. Мы подготовим информацию по выбранной модели.']]}
];
for(const m of markets){
 const path=`dist/${m.lang}/markets/${m.slug}`;fs.mkdirSync(path,{recursive:true});
 const url=`${origin}/${m.lang}/markets/${m.slug}/`;
 const faqJson=JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:m.faq.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))});
 const html=`<!doctype html><html lang="${m.lang}" dir="${m.dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(m.title)} | TANGZHENG</title><meta name="description" content="${escape(m.description)}"><link rel="canonical" href="${url}"><link rel="stylesheet" href="/style.css?v=20261004"><script type="application/ld+json">${faqJson}</script></head><body><header><a class="brand" href="/${m.lang}/">TANGZHENG<span>堂正 · ARCHITECTURAL PANELS</span></a><a class="nav-contact" href="#contact">CONTACT <span>↗</span></a></header><main class="market-main"><article class="market-page"><nav class="breadcrumbs"><a href="/${m.lang}/">TANGZHENG</a><span>/</span><span>${escape(m.slug.replaceAll('-',' '))}</span></nav><p class="eyebrow">TANGZHENG · MARKET SOLUTIONS</p><h1>${m.heading}</h1><p class="article-lede">${m.lead}</p><div class="market-keywords">${m.keywords.map(x=>`<span>${x}</span>`).join('')}</div><section class="market-columns"><div><p class="eyebrow">APPLICATIONS</p><h2>${m.lang==='ar'?'الاستخدامات المناسبة':m.lang==='ru'?'Основные применения':'Recommended applications'}</h2><ul>${m.uses.map(x=>`<li>${x}</li>`).join('')}</ul></div><div><p class="eyebrow">BEFORE ORDERING</p><h2>${m.lang==='ar'?'ما يجب تأكيده':m.lang==='ru'?'Что нужно согласовать':'Confirm before ordering'}</h2><ul>${m.checks.map(x=>`<li>${x}</li>`).join('')}</ul></div></section><section class="market-gallery"><img src="/assets/brick-hd.jpg" alt="${escape(m.keywords[1])}" width="1760" height="900"><img src="/assets/stone-hd.jpg" alt="${escape(m.keywords[0])}" width="1760" height="900"><img src="/assets/wood-hd.jpg" alt="${escape(m.keywords[2])}" width="1760" height="900"></section><section class="faq"><p class="eyebrow">FAQ</p>${m.faq.map(([q,a])=>`<h3>${q}</h3><p>${a}</p>`).join('')}</section><section class="article-cta" id="contact"><p class="eyebrow">PROJECT ENQUIRY</p><h2>${m.lang==='ar'?'أرسل متطلبات مشروعك':m.lang==='ru'?'Отправьте параметры проекта':'Send your project requirements'}</h2><p>${m.lang==='ar'?'اذكر نوع المبنى ورقم الموديل والكمية ومدينة التسليم.':m.lang==='ru'?'Укажите тип здания, код модели, количество и город доставки.':'Include the building type, model code, quantity and delivery city.'}</p><a class="button" href="mailto:15588869611@163.com?subject=${encodeURIComponent('TANGZHENG '+m.slug+' enquiry')}">15588869611@163.com <span>↗</span></a></section></article></main><footer><a class="brand" href="/${m.lang}/">TANGZHENG<span>堂正 · ARCHITECTURAL PANELS</span></a><p>+86 155 8886 9611</p><span>© 2026 TANGZHENG</span></footer></body></html>`;
 fs.writeFileSync(`${path}/index.html`,html);
}
const marketUrls=markets.map(m=>`${origin}/${m.lang}/markets/${m.slug}/`);
const sitemapUrls=[...Object.keys(catalog.languages).map(l=>`${origin}/${l}/`),`${origin}/en/blog/${articleSlug}/`,...marketUrls];
fs.writeFileSync('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+sitemapUrls.map(url=>`<url><loc>${url}</loc><lastmod>2026-10-04</lastmod></url>`).join('')+'</urlset>\n');
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
console.log('Built 12 fully rendered language pages, one English guide, root, sitemap and robots.txt');
