const assets=['wood','marble','brick','linear','stone','plain'];
const codes=['AM-058','MV-005','SBG-011','L-017','SV-003','PV-001'];
const email='15588869611@163.com';
const wa='https://wa.me/8615588869611';
let initial=new URLSearchParams(location.search).get('lang');
try{initial=initial||localStorage.getItem('zhengtang-language')}catch{}
initial=translations[initial]?initial:'en';
function render(lang){
 const t=translations[lang];document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
 document.title='TANGZHENG | '+t.eyebrow;document.querySelector('meta[name=description]').content=t.intro;
 document.querySelector('header').innerHTML=`<a class="brand" href="#">TANGZHENG<span>堂正 · ${t.brand}</span></a><nav aria-label="${t.nav[0]}">${['collection','performance','finishes','about'].map((id,i)=>`<a href="#${id}">${t.nav[i]}</a>`).join('')}</nav><div class="header-actions"><select class="language" aria-label="${t.lang}">${Object.entries(languages).map(([code,label])=>`<option value="${code}" ${code===lang?'selected':''}>${label}</option>`).join('')}</select><a class="nav-contact" href="#contact">${t.nav[4]} <span>↗</span></a></div>`;
 document.querySelector('.hero-copy').innerHTML=`<p class="eyebrow">${t.eyebrow}</p><h1>${t.title}</h1><p class="intro">${t.intro}</p><a class="button" href="#collection">${t.explore}<span>↗</span></a><div class="hero-note"><span>${t.exterior}</span><span>${t.origin}</span></div>`;
 document.querySelector('.material-art').setAttribute('aria-label',t.eyebrow);document.querySelector('.material-label').textContent=t.texture;
 document.querySelectorAll('.slab').forEach((el,i)=>el.alt=t.types[[0,4,2][i]]);
 document.querySelector('.spec-strip').innerHTML=`<div><strong>16<span> mm</span></strong><p>${t.metrics[0]}</p></div><div><strong>3.7<span> kg/m²</span></strong><p>${t.metrics[1]}</p></div><div><strong>3<span> ${t.metrics[3]}</span></strong><p>${t.metrics[2]}</p></div><p class="strip-note">${t.solution}</p>`;
 document.querySelector('#details').innerHTML=`<section class="mood-band" aria-label="${t.nav[2]}"><div><span>01</span><strong>${t.types[0]}</strong><small>${t.features[0]}</small></div><div><span>02</span><strong>${t.types[4]}</strong><small>${t.features[1]}</small></div><div><span>03</span><strong>${t.types[2]}</strong><small>${t.features[2]}</small></div></section><section class="section" id="collection"><div class="section-heading"><div><p class="eyebrow">01 / ${t.nav[0]}</p><h2>${t.collection}</h2></div><p>${t.collectionDesc}</p></div><div class="products">${assets.map((a,i)=>`<article class="product"><a href="mailto:${email}?subject=${encodeURIComponent('TANGZHENG '+codes[i]+' — '+t.types[i])}" aria-label="${t.nav[4]}: ${t.types[i]}"><div class="product-image"><img src="assets/${a}.jpg" alt="${t.types[i]}" loading="lazy" width="600" height="400"><span>${String(i+1).padStart(2,'0')}</span></div><div class="product-line"><h3>${t.types[i]}</h3><small>${codes[i]} ↗</small></div></a></article>`).join('')}</div></section>
 <section class="section performance" id="performance"><div><p class="eyebrow">02 / ${t.nav[1]}</p><h2>${t.performance}</h2><p>${t.construction}</p><div class="features">${t.features.map(x=>`<span>${x}</span>`).join('')}</div></div><div><dl class="spec-table">${t.specs.map((s,i)=>`<div><dt>${s}</dt><dd ${i<2?'dir="ltr"':''}>${t.values[i]}</dd></div>`).join('')}</dl><p class="note">${t.specNote}</p></div></section>
 <section class="section" id="finishes"><div class="section-heading"><div><p class="eyebrow">03 / ${t.nav[2]}</p><h2>${t.finishes}</h2></div></div><div class="finish-layout"><div class="finish-copy"><p>${t.finishDesc}</p><a class="text-link" href="mailto:${email}?subject=${encodeURIComponent('TANGZHENG — '+t.request)}">${t.request} ↗</a><p class="note">${t.colorNote}</p></div>${['colors','marble-colors'].map((a,i)=>`<div><img src="assets/${a}.jpg" alt="${t.sample}: ${t.colorNames[i]}" loading="lazy" width="600" height="800"><h3>${t.colorNames[i]}</h3></div>`).join('')}</div></section>
 <section class="section about" id="about"><div class="about-image"><div class="image-frame image-frame-wide"><img src="assets/house.jpg" alt="${t.project}" loading="lazy" width="500" height="400"><span>RESIDENTIAL</span></div><div class="image-frame image-frame-tall"><img src="assets/cabin.jpg" alt="${t.project}" loading="lazy" width="500" height="600"><span>RENOVATION</span></div></div><div class="about-copy"><p class="eyebrow">04 / ${t.nav[3]}</p><h2>${t.about}</h2><p>${t.aboutText}</p><div class="about-callout"><span>↗</span><div><h3>${t.aboutSub}</h3><p class="note">${t.aboutCaption}</p></div></div></div></section>
 <section class="section contact" id="contact"><div><p class="eyebrow">05 / ${t.nav[4]}</p><h2>${t.contact}</h2><p>${t.contactDesc}</p></div><div class="contact-details"><div><a href="tel:+8615588869611"><small>${t.phone}</small><bdi>+86 155 8886 9611</bdi></a><a href="mailto:${email}"><small>${t.email}</small><bdi>${email}</bdi></a><a class="button" href="${wa}" target="_blank" rel="noopener noreferrer">${t.whatsapp}<span>↗</span></a></div><div><a href="${wa}" target="_blank" rel="noopener noreferrer" aria-label="${t.whatsapp}"><img class="qr" src="assets/contact-qr.png" alt="${t.scan}" width="150" height="154"></a><p class="qr-label">${t.scan}</p></div></div></section>`;
 document.querySelector('footer').innerHTML=`<a class="brand" href="#">TANGZHENG<span>堂正 · ${t.brand}</span></a><p>${t.footer}</p><span>© 2026 TANGZHENG</span>`;
 document.querySelector('.language').addEventListener('change',e=>{const l=e.target.value;try{localStorage.setItem('zhengtang-language',l)}catch{};const u=new URL(location.href);u.searchParams.set('lang',l);history.replaceState(null,'',u);render(l)});
}
render(initial);
