const assets=['wood','marble','brick','linear','stone','plain'];
const codes=['AM-058','MV-005','SBG-011','L-017','SV-003','PV-001'];
const email='15588869611@163.com';
const wa='https://wa.me/8615588869611';
const chooser={en:['Choose a texture','Choose a colour reference','Selected','Enquire with this selection','Colour references are for browsing. Confirm the final finish with a physical sample.'],zh:['选择纹理样式','选择颜色编号','当前选择','带着所选款式咨询','网页色彩仅供初选，最终颜色请以实物样板确认为准。'],es:['Elija una textura','Elija un color','Selección','Consultar esta selección','Confirme el acabado final con una muestra física.'],fr:['Choisissez une texture','Choisissez une couleur','Sélection','Demander cette sélection','Validez la finition finale sur un échantillon physique.'],de:['Struktur wählen','Farbton wählen','Auswahl','Diese Auswahl anfragen','Endgültige Oberfläche anhand eines Musters bestätigen.'],pt:['Escolha a textura','Escolha a cor','Selecionado','Consultar esta seleção','Confirme o acabamento final com uma amostra física.'],ru:['Выберите фактуру','Выберите цвет','Выбрано','Запросить этот вариант','Подтвердите отделку по физическому образцу.'],ar:['اختر الملمس','اختر اللون','الاختيار','استفسر عن هذا الاختيار','يرجى تأكيد التشطيب النهائي بعينة فعلية.'],ja:['テクスチャを選択','カラーを選択','選択内容','この仕様で問い合わせる','最終色は実物サンプルでご確認ください。'],ko:['질감 선택','색상 선택','선택 항목','선택 사양 문의','최종 마감은 실물 샘플로 확인하세요.'],it:['Scegli la texture','Scegli il colore','Selezione','Richiedi questa selezione','Confermare la finitura con un campione fisico.'],hi:['टेक्सचर चुनें','रंग चुनें','चयन','इस चयन के बारे में पूछें','अंतिम फिनिश वास्तविक नमूने से सुनिश्चित करें।']};
const catalogPages=[
 ['catalog-04.jpg','Slate · Coarse brick · Long stone'],
 ['catalog-05.jpg','Standard brick grain · SBG-001—SBG-030'],
 ['catalog-06.jpg','Wide & narrow brick · Bark grain'],
 ['catalog-07.jpg','Marble grain · Corrugated grain'],
 ['catalog-08.jpg','Stone grain · Plain finish'],
 ['catalog-09.jpg','Oak grain · Great Wall · Stacked stone']
];
const catalogCopy={
 en:['Complete colour & style catalogue','Every finish and model shown in the product brochure. Open any sheet to zoom in, then quote the exact code when you contact us.','Open HD sheet','Ask about a catalogue model'],
 zh:['完整颜色与样式图册','彩页中的全部产品、颜色和型号均已上传。点击任意图页可高清放大，联系时请告知具体型号。','打开高清图页','咨询彩页型号'],
 es:['Catálogo completo de colores y estilos','Todos los acabados y modelos del catálogo. Abra una lámina para ampliarla e indique el código exacto al consultar.','Abrir lámina HD','Consultar un modelo'],
 fr:['Catalogue complet des couleurs et styles','Toutes les finitions et références de la brochure. Ouvrez une planche pour zoomer, puis indiquez la référence exacte.','Ouvrir la planche HD','Demander une référence'],
 de:['Vollständiger Farb- und Stilkatalog','Alle Oberflächen und Modelle aus dem Katalog. Blatt öffnen, vergrößern und bei der Anfrage den genauen Code angeben.','HD-Blatt öffnen','Katalogmodell anfragen']
};
let initial=new URLSearchParams(location.search).get('lang');
try{initial=initial||localStorage.getItem('zhengtang-language')}catch{}
initial=translations[initial]?initial:'en';
function render(lang){
 const t=translations[lang],c=chooser[lang],ct=catalogCopy[lang]||catalogCopy.en;document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
 document.title='TANGZHENG | '+t.eyebrow;document.querySelector('meta[name=description]').content=t.intro;
 document.querySelector('header').innerHTML=`<a class="brand" href="#">TANGZHENG<span>堂正 · ${t.brand}</span></a><nav aria-label="${t.nav[0]}">${['collection','performance','finishes','about'].map((id,i)=>`<a href="#${id}">${t.nav[i]}</a>`).join('')}</nav><div class="header-actions"><select class="language" aria-label="${t.lang}">${Object.entries(languages).map(([code,label])=>`<option value="${code}" ${code===lang?'selected':''}>${label}</option>`).join('')}</select><a class="nav-contact" href="#contact">${t.nav[4]} <span>↗</span></a></div>`;
 document.querySelector('.hero-copy').innerHTML=`<p class="eyebrow">${t.eyebrow}</p><h1>${t.title}</h1><p class="intro">${t.intro}</p><a class="button" href="#collection">${t.explore}<span>↗</span></a><div class="hero-note"><span>${t.exterior}</span><span>${t.origin}</span></div>`;
 document.querySelector('.material-art').setAttribute('aria-label',t.eyebrow);document.querySelector('.material-label').textContent=t.texture;
 document.querySelectorAll('.slab').forEach((el,i)=>el.alt=t.types[[0,4,2][i]]);
 document.querySelector('.spec-strip').innerHTML=`<div><strong>16<span> mm</span></strong><p>${t.metrics[0]}</p></div><div><strong>3.7<span> kg/m²</span></strong><p>${t.metrics[1]}</p></div><div><strong>3<span> ${t.metrics[3]}</span></strong><p>${t.metrics[2]}</p></div><p class="strip-note">${t.solution}</p>`;
 document.querySelector('#details').innerHTML=`<section class="mood-band" aria-label="${t.nav[2]}"><div><span>01</span><strong>${t.types[0]}</strong><small>${t.features[0]}</small></div><div><span>02</span><strong>${t.types[4]}</strong><small>${t.features[1]}</small></div><div><span>03</span><strong>${t.types[2]}</strong><small>${t.features[2]}</small></div></section><section class="section" id="collection"><div class="section-heading"><div><p class="eyebrow">01 / ${t.nav[0]}</p><h2>${t.collection}</h2></div><p>${t.collectionDesc}</p></div><h3 class="chooser-title">${c[0]}</h3><div class="products">${assets.map((a,i)=>`<article class="product ${i===0?'is-selected':''}"><button type="button" class="product-choice" data-style="${t.types[i]}" data-code="${codes[i]}" aria-pressed="${i===0?'true':'false'}"><div class="product-image"><img src="assets/${a}-hd.jpg" alt="${t.types[i]}" loading="lazy" width="1760" height="900"><span>${String(i+1).padStart(2,'0')}</span><b>✓</b></div><div class="product-line"><h3>${t.types[i]}</h3><small>${codes[i]}</small></div></button></article>`).join('')}</div><div class="catalog-intro"><p class="eyebrow">TANGZHENG · 堂正</p><h3>${ct[0]}</h3><p>${ct[1]}</p></div><div class="catalog-grid">${catalogPages.map((item,i)=>`<article class="catalog-sheet"><a href="/assets/catalog/${item[0]}" target="_blank" rel="noopener"><img src="/assets/catalog/${item[0]}" alt="${item[1]}" loading="lazy" width="2840" height="1800"><span>${ct[2]} ↗</span></a><div><small>${String(i+1).padStart(2,'0')}</small><h4>${item[1]}</h4><a href="mailto:${email}?subject=${encodeURIComponent('TANGZHENG catalogue — '+item[1])}">${ct[3]} →</a></div></article>`).join('')}</div><div class="colour-chooser"><div class="chooser-copy"><h3>${c[1]}</h3><p>${c[4]}</p></div><div class="swatches" role="group" aria-label="${c[1]}">${['ST-01','ST-02','ST-03','ST-04','ST-05','ST-06','ST-07','ST-08','MB-01','MB-02','MB-03','MB-04'].map((x,i)=>`<button type="button" class="swatch swatch-${i+1} ${i===0?'is-selected':''}" data-colour="${x}" aria-label="${x}" aria-pressed="${i===0?'true':'false'}"><span>${x}</span></button>`).join('')}</div></div><div class="selection-bar" data-label="${c[2]}"><div><small>${c[2]}</small><strong class="selection-value">${t.types[0]} · ${codes[0]} · ST-01</strong></div><a class="button selection-enquiry" data-email="${email}" data-prefix="TANGZHENG" href="mailto:${email}?subject=${encodeURIComponent('TANGZHENG '+codes[0]+' ST-01')}">${c[3]}<span>↗</span></a></div></section>
 <section class="section performance" id="performance"><div><p class="eyebrow">02 / ${t.nav[1]}</p><h2>${t.performance}</h2><p>${t.construction}</p><div class="features">${t.features.map(x=>`<span>${x}</span>`).join('')}</div></div><div><dl class="spec-table">${t.specs.map((s,i)=>`<div><dt>${s}</dt><dd ${i<2?'dir="ltr"':''}>${t.values[i]}</dd></div>`).join('')}</dl><p class="note">${t.specNote}</p></div></section>
 <section class="section" id="finishes"><div class="section-heading"><div><p class="eyebrow">03 / ${t.nav[2]}</p><h2>${t.finishes}</h2></div></div><div class="finish-layout"><div class="finish-copy"><p>${t.finishDesc}</p><a class="text-link" href="mailto:${email}?subject=${encodeURIComponent('TANGZHENG — '+t.request)}">${t.request} ↗</a><p class="note">${t.colorNote}</p></div>${['colors','marble-colors'].map((a,i)=>`<div><img src="assets/${a}.jpg" alt="${t.sample}: ${t.colorNames[i]}" loading="lazy" width="600" height="800"><h3>${t.colorNames[i]}</h3></div>`).join('')}</div></section>
 <section class="section about" id="about"><div class="about-image"><div class="image-frame image-frame-wide"><img src="assets/house.jpg" alt="${t.project}" loading="lazy" width="500" height="400"><span>RESIDENTIAL</span></div><div class="image-frame image-frame-tall"><img src="assets/cabin.jpg" alt="${t.project}" loading="lazy" width="500" height="600"><span>RENOVATION</span></div></div><div class="about-copy"><p class="eyebrow">04 / ${t.nav[3]}</p><h2>${t.about}</h2><p>${t.aboutText}</p><div class="about-callout"><span>↗</span><div><h3>${t.aboutSub}</h3><p class="note">${t.aboutCaption}</p></div></div></div></section>
 <section class="section contact" id="contact"><div><p class="eyebrow">05 / ${t.nav[4]}</p><h2>${t.contact}</h2><p>${t.contactDesc}</p></div><div class="contact-details"><div><a href="tel:+8615588869611"><small>${t.phone}</small><bdi>+86 155 8886 9611</bdi></a><a href="mailto:${email}"><small>${t.email}</small><bdi>${email}</bdi></a><a class="button" href="${wa}" target="_blank" rel="noopener noreferrer">${t.whatsapp}<span>↗</span></a></div><div><a href="${wa}" target="_blank" rel="noopener noreferrer" aria-label="${t.whatsapp}"><img class="qr" src="assets/contact-qr.png" alt="${t.scan}" width="150" height="154"></a><p class="qr-label">${t.scan}</p></div></div></section>`;
 document.querySelector('footer').innerHTML=`<a class="brand" href="#">TANGZHENG<span>堂正 · ${t.brand}</span></a><p>${t.footer}</p><span>© 2026 TANGZHENG</span>`;
 document.querySelector('.language').addEventListener('change',e=>{const l=e.target.value;try{localStorage.setItem('zhengtang-language',l)}catch{};const u=new URL(location.href);u.searchParams.set('lang',l);history.replaceState(null,'',u);render(l)});
}
render(initial);
